name: Sync repository

on:
  schedule:
  - cron: 0 0,6,12,18 * * *

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Checkout template mod
        uses: actions/checkout@v3
        with:
          repository: QuiltMC/quilt-template-mod
          fetch-depth: 0
          path: quilt-template-mod
    
      - name: Checkout kotlin template mod
        uses: actions/checkout@v3
        with:
          repository: QuiltMC/quilt-kotlin-template-mod
          fetch-depth: 0
          path: quilt-kotlin-template-mod

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.COZY_SSH_KEY }}
      
      - name: Set up identity file
        run: cp ./known_hosts ~/.ssh/known_hosts

      - name: Push template mod to Codeberg 
        run: |
          cd quilt-template-mod
          git push --force --mirror git@codeberg.org:QuiltMC/quilt-template-mod.git

      - name: Push kotlin template mod to Codeberg 
        run: |
          cd quilt-kotlin-template-mod
          git push --force --mirror git@codeberg.org:QuiltMC/quilt-kotlin-template-mod.git

      - name: Push template mod to Gitee 
        run: |
          cd quilt-template-mod
          git push --force --mirror git@gitee.com:quiltmc/quilt-template-mod.git

      - name: Push kotlin template mod to Codeberg 
        run: |
          cd quilt-kotlin-template-mod
          git push --force --mirror git@gitee.com:quiltmc/quilt-kotlin-template-mod.git
